<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('ITC Administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php if($this->zfcUserIdentity()): ?>
                        <div class='hello'>Hello <?php echo $this->zfcUserIdentity()->getDisplayname(); ?></div>
                    <?php endif ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/new-logo.png') ?>" alt="ITC Administration"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sites') ?></a></li>
                    <li class="active"><a href="<?php echo $this->url('useradmin') ?>"><?php echo $this->translate('Users') ?></a></li>
                    <li class="active"><a href="<?php echo $this->url('application') ?>"><?php echo $this->translate('Framework') ?></a></li>
                    <?php if($this->zfcUserIdentity()): ?>
                        <li class="active"><a href="/user/logout">Log out</a></li>
                    <?php endif ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <br>
        <div class="container">
            <?php
                // TODO: This seems kludgy, but I'm in a hurry.  This is loading the content, then checking authentication.
                // Get the current route to see if user needs to be logged in
                if (isset($_SERVER["REDIRECT_URL"])) :
                    $current_route = substr($_SERVER["REDIRECT_URL"],1);
                else:
                    $current_route = "website";
                endif;
                $whitelist = array(
                    "user/login",
                    "user/register",
                    "application"
                );
                // If User is logged in show content, else show the login
                if($this->zfcUserIdentity() || in_array($current_route,$whitelist)):
                    echo $this->content;
                else:
                    echo $this->zfcUserLoginWidget(array('redirect'=>$current_route));
                endif
            ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Industrial Training Consultants, Inc. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
    </body>
</html>

