<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ITC SSA &dash; Safety &bull; Specialty &bull; Awards')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js') // TODO: put versioned file here
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <!-- Navigation bar -->
        <?php
        // Initialize navbar items
        $this->mainMenu()->setItems([
            [
                'id' => 'users',
                'label' => 'Users',
                'link' => $this->url('users')
            ],
        ]);

        // Check if the activeMenuItemId passed to layout view model
        // and if so, use it for setting active navbar item.
        if (isset($activeMenuItemId)) {
            $this->mainMenu()->setActiveItemId($activeMenuItemId);
        }

        // Render the navbar
        echo $this->mainMenu()->render($this->identity());
        echo $this->pageBreadcrumbs()->render();
        ?>
        <div class="container">
            <?php
                echo $this->content;
            ?>
            <br><br><br>
            <hr>
            <footer>
                <div class="row">
                        <div class="col-md-3">
                            <?php // TODO: ID=1 below should be passed in from the view? or controller or module? ?>
                            <a href="<?= $this->url('posts',
                                    ['action'=>'view', 'id'=>2],
                                    ['fragment'=>'top']
                                ); ?>">
                                Click here to learn more
                            </a>
                        </div>
                        <div class="col-md-3-right">
                            &copy; <?php echo date('Y') ?>
                            by Industrial Training Consultants, Inc.
                        </div
                        <div class="col-md-3">
                        </div>
                </div>                   
            </footer>
        </div> <!-- /container -->
    </body>
</html>

